name: getx_boilerplate
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0
  get: ^4.6.6 # for state managment and context less stuff
  logger: ^2.0.2+1 # log events in clear way insted of (print)
  readmore: ^2.2.0
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.2
  flutter_phoenix: ^1.1.1
  internet_connection_checker_plus: ^2.1.0
  dio: ^5.4.0  # for api requests
  # pretty_dio_logger:  # for dio api logging and debugging
  hive: ^2.2.3  # local database (SQFlite replacement)
  hive_flutter: ^1.1.0 # make it easy to use hive (no need for path provider)
  get_storage: ^2.1.1 # shared preferences replacement (sync)
  firebase_core: ^2.24.2  # to initialize firebase services
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.9  # fcm services
  awesome_notifications: ^0.8.3 # notifications services (will be used for fcm)
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.7  # generate dart files
  hive_generator: ^2.0.1 # generate hive files

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/svgs/